/*
 * Copyright (c) 2026, GP Interactive (GamePlanet Interactive)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define PROGRAM_NAME "bforth"
#define STACK_SIZE 1024
#define MEMORY_SIZE 65536
#define MAX_TOKEN_LEN 256

int function_counter = 0;

void write_header(FILE *out) {
    fprintf(out, "/* Generated by %s */\n", PROGRAM_NAME);
    fprintf(out, "#include <stdio.h>\n");
    fprintf(out, "#include <stdlib.h>\n\n");
    fprintf(out, "long memory[%d] = {0};\n", MEMORY_SIZE);
    fprintf(out, "long stack[%d];\n", STACK_SIZE);
    fprintf(out, "int top = -1;\n\n");
    fprintf(out, "void fth_block_0(void) {\n");
}

void write_footer(FILE *out) {
    fprintf(out, "}\n\n");
    
    fprintf(out, "int main(void) {\n");
    for(int i = 0; i <= function_counter; i++) {
        fprintf(out, "    fth_block_%d();\n", i);
    }
    fprintf(out, "    return 0;\n");
    fprintf(out, "}\n");
}

int main(int argc, char *argv[]) {

    if(argc < 3) {
        fprintf(stderr, "%s: error: insufficient arguments\n", PROGRAM_NAME);
        fprintf(stderr, "Usage: %s <input_file.fth> <output_file.c>\n", PROGRAM_NAME);
        return 1;
    }

    FILE *in = fopen(argv[1], "r");
    if(!in){
        fprintf(stderr, "%s: error: failed to open input file '%s'\n", PROGRAM_NAME, argv[1]);
        perror("reason");
        return 1;
    }

    FILE *out = fopen(argv[2], "w");
    if(!out) {
        fprintf(stderr,"%s: error: failed to create output file '%s'\n", PROGRAM_NAME, argv[2]);
        perror("reason");
        fclose(in);
        return 1;
    }

    printf("Files successfully opened. Starting transpilation...\n");
    write_header(out);

    char token[MAX_TOKEN_LEN];
    int in_definition = 0;

    while(fscanf(in, "%255s", token) != EOF) {
        if(strcmp(token, "\\") == 0) {
            int ch;
            while((ch = fgetc(in)) != '\n' && ch != EOF);
            continue;
        }

        if(strcmp(token, ":") == 0){
            char name[MAX_TOKEN_LEN];
            if(fscanf(in, "%255s", name) != EOF){
               fprintf(out, "}\n\n"); 
               fprintf(out, "void fth_%s(void) {\n", name);
               in_definition = 1;
            }
            continue;
        }
        else if(strcmp(token, ";") == 0) {
            if(in_definition) {
                fprintf(out, "}\n\n"); 
                function_counter++;
            
                fprintf(out, "void fth_block_%d(void) {\n", function_counter);
                in_definition = 0;
            }
            continue;
        }
        else if (strcmp(token, "0BRANCH") == 0 || strcmp(token, "0branch") == 0) {
             char lbl_num[MAX_TOKEN_LEN];
             if (fscanf(in, "%255s", lbl_num) != EOF) {
                 fprintf(out, "    if (top >= 0 && stack[top--] == 0) goto label_fth_%s;\n", lbl_num);
             }
        }
        else if (strncmp(token, "LABEL", 5) == 0 || strncmp(token, "label", 5) == 0) { 
             fprintf(out, "label_fth_%s:\n", token + 5);
        }
        else if (strcmp(token, "@") == 0 || strcasecmp(token, "FETCH") == 0) {
             fprintf(out, "    if (top >= 0 && stack[top] >= 0 && stack[top] < %d) { stack[top] = memory[stack[top]]; }\n", MEMORY_SIZE);
        }
        else if (strcmp(token, "!") == 0 || strcasecmp(token, "STORE") == 0) {
             fprintf(out, "    if (top >= 1 && stack[top] >= 0 && stack[top] < %d) { memory[stack[top]] = stack[top-1]; top -= 2; }\n", MEMORY_SIZE);
        }
        else if(strcmp(token, "+") == 0) {
             fprintf(out, "    if (top >= 1) { stack[top-1] += stack[top]; top--; }\n");
        }
        else if (strcmp(token, "-") == 0) {
            fprintf(out, "    if (top >= 1) { stack[top-1] -= stack[top]; top--; }\n");
        }
        else if (strcmp(token, "=") == 0){
            fprintf(out, "    if (top >= 1) { stack[top-1] = (stack[top-1] == stack[top]) ? -1 : 0; top--; }\n");
        }
        else if(strcmp(token, "DUP") == 0 || strcmp(token, "dup") == 0) {
          fprintf(out, "    if (top >= 0 && top < %d) { stack[top+1] = stack[top]; top++; }\n", STACK_SIZE - 1);
        }
        else if(strcmp(token, "DROP") == 0 || strcmp(token, "drop") == 0) {
            fprintf(out, "    if (top >= 0) { top--; }\n");
        }
        else if(strcmp(token, "SWAP") == 0 || strcmp(token, "swap") == 0) {
            fprintf(out, "    if (top >= 1) { long t = stack[top]; stack[top] = stack[top-1]; stack[top-1] = t; }\n");
        }
        else if (strcasecmp(token, "AND") == 0) {
            fprintf(out, "    if (top >= 1) { stack[top-1] &= stack[top]; top--; }\n");
        }
        else if(strcmp(token, ".") == 0){
            fprintf(out, "    if (top >= 0) { printf(\"%%ld \", stack[top--]); fflush(stdout); }\n");
        }
        else if(strcmp(token, "CR") == 0 || strcmp(token, "cr") == 0) {
            fprintf(out, "    printf(\"\\n\");\n");
        }
        else if(strcasecmp(token, "KEY") == 0) {
            fprintf(out, "    if (top < %d) { stack[++top] = getchar(); }\n", STACK_SIZE - 1);
        }
        else if(strcasecmp(token, "EMIT") == 0) {
            fprintf(out, "    if (top >= 0) { putchar((char)stack[top--]); fflush(stdout); }\n");
        }
        else {
            char *endptr;
            long val = strtol(token, &endptr, 0);
            if(*endptr == '\0') {
                fprintf(out, "    if (top < %d) { stack[++top] = %ld; }\n", STACK_SIZE - 1, val);
            } else { 
                fprintf(out, "    void fth_%s(void); fth_%s();\n", token, token);
            }
        }
    }

    write_footer(out);
    fclose(in);
    fclose(out);
    printf("Transpilation finished successfully!\n");
    return 0;
}
